version: "3.7"
services:
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: keycloak
    ports:
      - "11080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - DB_VENDOR=h2
